# Generated by Django 5.0.6 on 2024-06-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '0002_remove_position_department_alter_employee_department_and_more'),
        ('holidays', '0002_rename_aproved_by_holidayrequest_approved_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
