# Generated by Django 5.0.6 on 2024-06-05 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employees_city_employees_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hire_date',
            field=models.DateField(default=datetime.date(2024, 6, 5)),
        ),
    ]
